site_name: Bearhouse Doco
site_description: Production-shaped homelab architecture and operations documentation
site_author: Tom Busby
site_url: https://tbusby.github.io/bearhouse-doco

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.path
    # - toc.integrate
    - content.code.copy
    - search.suggest
    - search.highlight
#   icon:
#     logo: material/teddy-bear
  logo: assets/bearhouse-logo.png
  palette: 
      scheme: slate
      primary: custom
      accent: custom
  language: en

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - javascripts/mermaid-init.js

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - blog

nav:
  - Home: index.md
  - Architecture:
      - Overview: architecture/overview.md
      - Principles: architecture/principles.md
      - Decisions Summary: architecture/decisions.md
      - Diagrams: architecture/diagrams.md
  - Infrastructure:
      - Proxmox: infrastructure/proxmox.md
      - Virtual Machines: infrastructure/virtual-machines.md
      - Ubuntu 2404 Cloud Init Template: infrastructure/ubuntu-cloud-image-template.md
      - Networking: infrastructure/networking.md
      - Storage: infrastructure/storage.md
      - Security Baseline: infrastructure/security-baseline.md
      - ops1 Admin Node: infrastructure/ops1-admin-node.md 
      - Secrets Management: infrastructure/secrets-management.md
      - Observability: infrastructure/observability.md
      - Kubernetes Storage: infrastructure/k8s-storage.md
  - Kubernetes:
      - Cluster Design: kubernetes/cluster-design.md
      - Platform Services: kubernetes/platform-services.md
      - GitOps: kubernetes/gitops.md
      - Secrets Management: kubernetes/secrets-management.md
      - Initial Setup:
          - Kubernetes Initial Setup: kubernetes/initial-setup/kubernetes-initial-setup.md
          - Kubernetes Metrics Server: kubernetes/initial-setup/kubernetes-metrics-server.md
          - MetalLB install: kubernetes/initial-setup/metallb.md
          - Ingress-nginx: kubernetes/initial-setup/ingress-nginx.md
          - Certificate Management: kubernetes/initial-setup/certificate-manager.md
          - K8s Storage Setup: kubernetes/initial-setup/k8s-storage-setup.md
  - Operations:
      - CI/CD: operations/ci-cd.md
      - Observability: operations/observability.md
      - Backup & Recovery: operations/backup-recovery.md
      - Patching & Upgrades: operations/patching-upgrades.md
      - Configuration Management: operations/config-management.md
      - Node Bootstrap: operations/node-bootstrap.md
      - Initial Setup:
        #   - Proxmox Setup: operations/initial-setup/proxmox-setup.md
          - Proxmox Short Runbook: operations/initial-setup/proxmox-short-runbook.md
  - Runbooks:
      - Runbooks Index: runbooks/index.md
      - Runbook Template: runbooks/000-template.md
      - Ansible Config Management: runbooks/001-ansible.md
      - Kubernetes Init: runbooks/002-kubernetes-init.md
      - Rebuild ops1: runbooks/003-rebuild-ops.md
  - Standards:
      - Naming Standards: standards/naming-standards.md
      - Repository Structure: standards/repository-structure.md
      - Change Management: standards/change-management.md
      - Ansible Repository Structure: standards/ansible-repo-structure.md
  - ADRs:
      - ADR Index: adr/index.md
      - ADR Template: adr/0000-template.md
      - ADR-0001 Proxmox: adr/0001-use-proxmox-as-hypervisor.md
      - ADR-0002 kubeadm: adr/0002-use-kubeadm-for-kubernetes-bootstrap.md
      - ADR-0003 Cilium: adr/0003-use-cilium-as-cni.md
      - ADR-0004 NFS Storage: adr/0004-use-nfs-for-initial-persistent-storage.md
      - ADR-0005 GitHub Actions + Argo CD: adr/0005-use-github-actions-and-argocd-for-delivery.md
      - ADR-0006 SOPS + age: adr/0006-use-sops-and-age-for-secrets.md
      - ADR-0007 MetalLB: adr/0007-melatllb.md
      - ADR-0008 Ingress-Nginx: adr/0008-ingress-nginx.md
      - ADR-0009 Cert Manager: adr/0009-cert-manager.md
      - ADR-0010 Prometheus & Grafana: adr/0010-kube-prometheus-stack.md
      - ADR-0011 k8s Storage: adr/0011-k8s-storage.md
  - Blog:
    - blog/index.md
    